package install

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"time"

	"github.com/speakeasy-api/agenthooks"
)

// openclawHooksFor maps subscribed unified kinds to OpenClaw typed plugin
// hook names. KindStop also subscribes llm_output: agent_end carries no final
// message or usage, so the shim caches the turn's llm_output and splices
// finalMessage/usage into the agent_end frame (mirroring the OpenCode
// session.idle splice).
var openclawKindHooks = map[agenthooks.EventKind][]string{
	agenthooks.KindToolPre:         {"before_tool_call"},
	agenthooks.KindToolPost:        {"after_tool_call"},
	agenthooks.KindPromptSubmitted: {"before_agent_run"},
	agenthooks.KindSessionStart:    {"session_start"},
	agenthooks.KindSessionEnd:      {"session_end"},
	agenthooks.KindStop:            {"agent_end", "llm_output"},
	agenthooks.KindSubagentStart:   {"subagent_spawned"},
	agenthooks.KindSubagentStop:    {"subagent_ended"},
	agenthooks.KindModelRequest:    {"llm_input"},
	agenthooks.KindModelResponse:   {"llm_output"},
	agenthooks.KindCompactPre:      {"before_compaction"},
	agenthooks.KindCompactPost:     {"after_compaction"},
}

// renderOpenClaw writes a native OpenClaw plugin (openclaw.plugin.json +
// package.json + index.js) that proxies typed api.on hooks to the consumer binary over
// NDJSON stdio (agenthooks serve --provider=openclaw). Install the rendered
// directory with `openclaw plugins install <dir>` and restart the Gateway.
// Conversation-scope hooks (before_agent_run, llm_*, agent_end) additionally
// require plugins.entries.<id>.hooks.allowConversationAccess: true in the
// OpenClaw config (quirk #35).
func renderOpenClaw(m Manifest, _ Target) (fs.FS, error) {
	cmd, err := json.Marshal(m.Command)
	if err != nil {
		return nil, err
	}

	seen := map[string]bool{}
	var hooks []string
	for _, spec := range m.Hooks {
		for _, h := range openclawKindHooks[spec.Kind] {
			if !seen[h] {
				seen[h] = true
				hooks = append(hooks, h)
			}
		}
	}
	hooksJSON, err := json.Marshal(hooks)
	if err != nil {
		return nil, err
	}

	// The shim owns the gate deadline: OpenClaw applies no default timeout to
	// typed hook handlers (quirk #36), so an unbounded consumer would stall
	// the agent turn indefinitely.
	gateTimeout := 10 * time.Second
	for _, spec := range m.Hooks {
		if spec.Blocking && spec.Timeout > gateTimeout {
			gateTimeout = spec.Timeout
		}
	}

	id := m.Identity.Name
	if id == "" {
		id = "agenthooks"
	}
	name := m.Identity.Name
	if name == "" {
		name = "agenthooks"
	}
	desc := m.Identity.Description
	if desc == "" {
		desc = "Proxies OpenClaw plugin hooks to the agenthooks consumer binary."
	}
	version := m.Identity.Version
	if version == "" {
		version = "0.0.0"
	}

	manifest, err := jsonFile(map[string]any{
		"id":          id,
		"name":        name,
		"description": desc,
		"version":     version,
		"configSchema": map[string]any{
			"type":                 "object",
			"additionalProperties": false,
			"properties":           map[string]any{},
		},
		"activation": map[string]any{"onStartup": true},
	})
	if err != nil {
		return nil, err
	}

	// The package.json openclaw.extensions entry is what `openclaw plugins
	// install` keys plugin detection on — without it the installer falls back
	// to hook-pack detection and rejects the directory (HOOK.md missing). The
	// entry must be plain JavaScript: package installs reject TypeScript
	// entries ("compiled runtime output required"); TS is dev-path only.
	pkg, err := jsonFile(map[string]any{
		"name":     "openclaw-plugin-" + id,
		"version":  version,
		"type":     "module",
		"private":  true,
		"openclaw": map[string]any{"extensions": []string{"./index.js"}},
	})
	if err != nil {
		return nil, err
	}

	shim := fmt.Sprintf(openClawShimTemplate,
		string(cmd), string(hooksJSON), gateTimeout.Milliseconds(),
		m.Fail == agenthooks.FailClosed,
		jsString(id), jsString(name), jsString(desc))
	return memFS(map[string][]byte{
		"openclaw.plugin.json": manifest,
		"package.json":         pkg,
		"index.js":             []byte(shim),
	}), nil
}

func jsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

const openClawShimTemplate = `// Generated by agenthooks install — do not edit.
// Proxies OpenClaw typed plugin hooks to the consumer binary over NDJSON
// stdio (agenthooks serve --provider=openclaw). Frames: {seq, hook, event,
// ctx} -> {seq, output?}; the reply output is returned verbatim as the hook
// handler's return value (block/requireApproval/params on before_tool_call,
// the gate decision on before_agent_run). Plain JavaScript: OpenClaw package
// installs reject TypeScript entry modules.
import { spawn } from "node:child_process"
import { createInterface } from "node:readline"

const COMMAND = %s
const HOOKS = %s
const GATE_TIMEOUT_MS = %d
const FAIL_CLOSED = %t
// Gating hooks await the reply inside the shim-owned deadline; every other
// hook is fire-and-forget so telemetry never stalls the agent turn.
const GATE_HOOKS = new Set(["before_tool_call", "before_agent_run"])

export default {
  id: %s,
  name: %s,
  description: %s,
  register(api) {
    const child = spawn(COMMAND[0], [...COMMAND.slice(1), "agenthooks", "serve", "--provider=openclaw"], {
      stdio: ["pipe", "pipe", "inherit"],
    })
    let seq = 0
    const pending = new Map()
    // agent_end carries no final message or usage; cache the turn's
    // llm_output and splice it into the agent_end frame.
    const llmByRun = new Map()

    createInterface({ input: child.stdout }).on("line", (line) => {
      if (!line.trim()) return
      let reply
      try {
        reply = JSON.parse(line)
      } catch {
        return
      }
      const resolve = pending.get(reply.seq)
      if (!resolve) return
      pending.delete(reply.seq)
      resolve(reply)
    })
    child.on("exit", () => {
      for (const [, resolve] of pending) resolve({})
      pending.clear()
    })

    const call = (hook, event, ctx) => {
      if (child.exitCode !== null || !child.stdin?.writable) return Promise.resolve({})
      const id = ++seq
      child.stdin.write(JSON.stringify({ seq: id, hook, event, ctx }) + "\n")
      return new Promise((resolve) => {
        pending.set(id, resolve)
        const timer = setTimeout(() => {
          if (pending.delete(id)) resolve({ timedOut: true })
        }, GATE_TIMEOUT_MS)
        if (typeof timer.unref === "function") timer.unref()
      })
    }

    const sanitizeCtx = (hook, ctx) => {
      if (hook !== "gateway_start" && hook !== "gateway_stop") return ctx
      // Gateway hooks hand plugins the full config including auth secrets
      // (observed 2026.6.34); never forward it.
      return { port: ctx?.port, workspaceDir: ctx?.workspaceDir }
    }

    for (const hook of HOOKS) {
      api.on(hook, (event, ctx) => {
        if (hook === "llm_output") {
          const texts = Array.isArray(event?.assistantTexts) ? event.assistantTexts : []
          const key = event?.runId ?? event?.sessionId ?? ""
          llmByRun.set(key, { finalMessage: texts.join("\n") || undefined, usage: event?.usage })
          void call(hook, event, sanitizeCtx(hook, ctx))
          return
        }
        if (hook === "agent_end") {
          const cached = llmByRun.get(event?.runId ?? "") ?? llmByRun.get(ctx?.sessionId ?? "")
          if (event?.runId) llmByRun.delete(event.runId)
          const spliced = cached ? { ...event, finalMessage: cached.finalMessage, usage: cached.usage } : event
          void call(hook, spliced, sanitizeCtx(hook, ctx))
          return
        }
        if (!GATE_HOOKS.has(hook)) {
          void call(hook, event, sanitizeCtx(hook, ctx))
          return
        }
        return call(hook, event, sanitizeCtx(hook, ctx)).then((reply) => {
          if (reply?.timedOut && FAIL_CLOSED) {
            if (hook === "before_agent_run") {
              return { outcome: "block", reason: "agenthooks: hook timed out (fail-closed)" }
            }
            return { block: true, blockReason: "agenthooks: hook timed out (fail-closed)" }
          }
          return reply?.output
        })
      })
    }

    api.on("gateway_stop", () => {
      try {
        child.stdin.end()
        child.kill()
      } catch {}
    })
  },
}
`
